#!/usr/bin/env bash
## -*- sh-basic-offset: 2 -*-
set -x

if [ ! -d "be-tree" ]; then
#    git clone -b 'v1.3.0' --single-branch --depth 1 http://github.com/adgear/be-tree
#    git clone -b 'sub_is_enclosed' --single-branch --depth 1 http://github.com/adgear/be-tree
    git clone -b 'PEDSP-5590' --single-branch --depth 1 http://github.com/adgear/be-tree
    cd be-tree
    make NIF=true
fi

