% -define(CLOCK_REALTIME, 0).
-define(CLOCK_MONOTONIC, 1).
% -define(CLOCK_PROCESS_CPUTIME_ID, 2).
% -define(CLOCK_THREAD_CPUTIME_ID, 3).

-define(THRESHOLD_1_000_MICROSECONDS, 1_000).
-define(THRESHOLD_0_MICROSECONDS, 0).